### ISSUE TITLE
Data List not saving single values (Dropdown List, Radio Button List) in Umbraco 9.3.0

### ISSUE THREAD

**Issue by AaronSadlerUK** [leekelleher/umbraco-contentment#200] opened 2022-02-11 23:40 UTC
### Which Contentment version are you using?

3.1.0

### Which Umbraco version are you using? For example: 8.14.1 - don't just write v8

9.3.0

### Bug summary

The value gets lost while saving

### Steps to reproduce

Watch video :)

https://user-images.githubusercontent.com/9937803/153685042-17c42ce6-6b3a-4877-9fae-8793ce3a5979.mp4

### Do you have Umbraco ModelsBuilder enabled?

- [X] Yes, it is enabled.

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by leekelleher** [comment] 2022-02-12 09:32
@AaronSadlerUK Thanks for reporting this.

A few questions so I can try reproduce the issue.

- This happens inside the Block List editor?
- We're there any JS errors in dev tools/console?
- Is this an upgrade of Contentment? e.g. was it working previously?

**Comment by leekelleher** [comment] 2022-02-13 13:40
Thanks @AaronSadlerUK. I'm getting a feeling that something may have changed in the Block List editor recently. 🤔 I'll investigate. 👍

**Comment by leekelleher** [comment] 2022-02-14 11:11
I can reproduce the issue on Umbraco v9.3.0.

The frustrating part is that I've tested this on v9.0.0 (this morning) and it worked fine (inside Block List).
_I'll continue investigating..._ 🧐

**Comment by leekelleher** [comment] 2022-02-14 11:54
Okay, it appears to be when a Data List is configured to use a list-editor that stores a single value, e.g. dropdown list or radiobuttons.

Because Data List's underlying data-editor value type is set to JSON, the single string values appear to now be encoded as JSON strings, e.g. what used to be `"value"` is now `"\"value\""`. Meaning that the list-editor treats that as the literal value and can't populate the dropdown/radiobutton. 😫

My gut feeling is these changes in v9.3.0 - https://github.com/umbraco/Umbraco-CMS/pull/11806 - but I can't be sure. It feels quite far down the rabbit hole, _(e.g. I'd lose a dev day just investigating it.)_

The Data List editors that store multiple values, e.g. Item Picker, Checkbox List, etc - they all appear to still work in v9.3.0.

I'll explore my options for a workaround/fix.

**Comment by leekelleher** [comment] 2022-02-14 12:31
Linking for cross-reference: https://github.com/umbraco/Umbraco-CMS/issues/11989

**Comment by leekelleher** [comment] 2022-02-17 12:46
Fingers crossed, this is resolved in Umbraco v9.3.1 🤞 
re: https://github.com/umbraco/Umbraco-CMS/pull/12015

**Comment by AaronSadlerUK** [comment] 2022-02-17 12:49
Ok great, I'm not sure when 9.3.1 is penned for release.

Do you know if they will be adding an RC or Prerelease to test?

**Comment by ronaldbarendse** [comment] 2022-02-17 13:06
@leekelleher We've identified this issue as a regression and will fix it in 9.3.1 that's indeed scheduled for next Tuesday (and you're also right that we don't release RCs for patches).

Sorry for the inconvenience!

**Comment by andyneil** [comment] 2022-02-20 11:29
I can confirm that 9.3.1 does indeed fix this. 
I updated to the pre-release using the instructions in this blog post to test:
https://umbraco.com/blog/umbraco-9-beta-release/

**Comment by leekelleher** [comment] 2022-02-20 11:38
@andyneil Thanks for confirming! 👍

**Comment by AaronSadlerUK** [comment] 2022-02-22 23:00
I can confirm 9.3.1 fixed this for me 🙂

**Closed** 2022-02-22 23:00 UTC
Labels: bug-report, umbraco
