### ISSUE TITLE
Data List: Item Picker - Reselecting an item after validation error breaks save and publish

### ISSUE THREAD

**Issue by Ambertvu** [leekelleher/umbraco-contentment#242] opened 2022-08-02 08:43 UTC
### Which Contentment version are you using?

4.1.1

### Which Umbraco version are you using? For example: 8.14.1 - don't just write v8

10.0.0 and 10.0.1 clean

### Bug summary

Save and publish breaks when Item picker entry is invalid.

### Steps to reproduce

Create a contentment datatype with a datasource (don't think this matters) and a Item picker (this matters) (tried it with default values).

Create a documenttype with the datatype set as required.
Create a content item with the datatype.

Go to the content, select the documentType, select a value in your created dataType, save and publish.
It saves correctly

Deselect the value, click save and publish.
Error appears that the value is required as expected.
In console a PostSave 400 error appears.
When re-selecting a value and clicking save and publish, the button no longer works.

First clicking save and then save and publish(or reloading the page) fixes it again.

### Expected result / actual result

Clicking save and publish should still work after reselecting a value after a validation error.

### Do you have Umbraco ModelsBuilder enabled?

- [ ] Yes, it is enabled.

### What browsers are you seeing the problem on?

Firefox, Chrome

**Comment by leekelleher** [comment] 2022-08-02 19:53
@Ambertvu Thanks for raising this, I can reproduce the bug. 👍 
Now to figure out why the Item Picker editor is doing that. 😆

**Comment by leekelleher** [comment] 2022-08-04 09:21
Well, I'm stumped. 😖  I've deep dived into Umbraco source to try to figure out why the validity isn't being reset after a new value is selected, but I'm no closer to figuring out why it doesn't work... and I couldn't find any documentation on property-editor validation (specifically).

Adding the **help-wanted** label. I'm laying my hopes on someone out there has experienced this before, somehow. 😬

**Comment by mennomout** [comment] 2022-10-27 14:14
@leekelleher I can confirm that this issue also excists for non-contentment data types. I made a new data type with a checkbox list and the same issue occurs when making it required and then pressing save & publish.

**Comment by leekelleher** [comment] 2022-10-28 08:52
@mennomout Thank you for confirming this. 👍 

Do you know if this bug has been reported with [Umbraco-CMS](https://github.com/umbraco/Umbraco-CMS/)? If so, I'll cross-link to it.

**Comment by mennomout** [comment] 2022-11-16 12:38
@leekelleher Sorry for the late response. But yes the issue you linked seems to be the one that is connected to this one.

**Comment by leekelleher** [comment] 2022-12-21 12:02
I'm closing this issue, as it appears to be an underlying issue with Umbraco CMS, (please see https://github.com/umbraco/Umbraco-CMS/issues/13082). I have tried to see if I can resolve or workaround the issue within the Contentment codebase, but no success.

**Comment by leekelleher** [comment] 2023-02-22 14:44
Reopening this issue. Whilst on an unrelated project, I hit a similar issue and finally figured it out.

It's all to do with the initial/default value set by the [`DataValueEditor.ToEditor`](https://github.com/umbraco/Umbraco-CMS/blob/release-10.0.0/src/Umbraco.Core/PropertyEditors/DataValueEditor.cs#L255). Of which, Data List uses Umbraco's `DataValueEditor` so would default to an empty string `""` whereas ideally it should be an empty array `[]`.

I'll patch up a fix in due course.

**Comment by leekelleher** [comment] 2023-10-09 13:49
Closing issue. I'd forgotten that I'd already fixed this in commit e685cb8fc03aebc5eb3495fe1e247904ef5179da. 🤦 It was already released in Contentment v4.4.2.

**Closed by leekelleher** 2023-10-09 13:49 UTC
Labels: bug-report

**Comment by Ambertvu** [comment] 2023-11-20 14:26
Hi Lee

I've just tested this in 10.7.0 with Contentment 4.5.0, and it seems the issue still appears.

However you cannot 'deselect' a required value anymore, so a part of it seems fixed.
But when creating a content item using the contenttype, and not selecting an value for the item picker, and saving, you'll get the postSave error still

**Comment by Ambertvu** [comment] 2024-12-06 09:33
Hi @leekelleher.

This still seems to be exactly the same running Contentment.Core 4.7.0 and Umbraco 13.5.2.

Should I make a new issue?
