### ISSUE TITLE
Contentment v3.0.0-alpha002 installation

### ISSUE THREAD

**Issue by Antoshjkee** [leekelleher/umbraco-contentment#124] opened 2021-07-09 13:56 UTC
### What is the current behaviour?
By installing Contentment v3.0.0-alpha002 version from the NuGet, the **`App_Plugins/Contentment`** folder does not get copied.
I have gone and copied **`App_Plugins`** manually from ZIP source and some files are missing. Particularly views in **`App_Plugins/Contentment/editors`** folder.

### What is the expected behaviour?
**`/App_Plugins/Contentment`** folder to get copied on NuGet install.

### What is the motivation/use case for changing the behaviour?
Bug?

### Please tell us about your set-up:

- Contentment version: 3.0.0-alpha002
- Umbraco version: 9.0.0-rc
- Umbraco ModelsBuilder _(if applicable?)_ is: enabled
- Browser _(if applicable?)_: N/A

### Anything else?
Maybe it's just me. I have tried to reinstall it, have tried restore packages. Nothing helps.

**Comment by leekelleher** [comment] 2021-07-09 16:02
Thanks @Antoshjkee. I can confirm that I can reproduce the issue. I'm looking into a fix.

**Comment by bergmania** [comment] 2021-07-09 16:06
FYI, What Umbraco does, is copying on build, by adding msbuild targets, in a buildTransitive/{nugetpackagename}.targets file

**Comment by leekelleher** [comment] 2021-07-09 16:12
@bergmania Does this mean that each Umbraco Package is responsible for copying over the App_Plugins subfolder on install?
Do you know if there is any documentation about `buildTransitive/{nugetpackagename}.targets`?

Strange that I didn't have to do this for previous NuGet packages (of my Umbraco packages). Feel like I've completely missed something here. 😕

**Comment by bergmania** [comment] 2021-07-09 16:22
The main reason is because content copy is not official supported by nuget anymore. Now content is symbolic links to the cache that is copied on build, but this is not useful for websites.  I don’t have a link currently, as I’m writing from phone, but most information is about build/{nugetpackagename}.targets. But this only execute on directly referenced package, and thereby not useful for starter kits.. The Umbraco Package template has this implemented by default

**Comment by leekelleher** [comment] 2021-07-09 16:32
Thanks @bergmania, no worries about docs link - I've found various info about it. 👍 

I didn't use the Umbraco Package Template - mostly because I couldn't figure out how to retrofit my exiting package code/proj into it (or at least to the point where I was happy with it). I'll take another look at it (to see what I need to replicate).

**Comment by leekelleher** [comment] 2021-07-09 17:28
@Antoshjkee This has now been resolved in [`v3.0.0-alpha003`](https://www.nuget.org/packages/Our.Umbraco.Community.Contentment.Core/3.0.0-alpha003).

Thanks again for raising it, my testing my local demo site missed this, (as the App_Plugins was already there), serves me right for not testing the NuGet package on a clean fresh install. 🤦

**Closed by leekelleher** 2021-07-09 17:28 UTC
Labels: bug-report
