### ISSUE TITLE
DataList property ignores user permissions

### ISSUE THREAD

**Issue by jerpenol** [leekelleher/umbraco-contentment#318] opened 2023-05-12 11:44 UTC
### Which Contentment version are you using?

4.4.3

### Which Umbraco version are you using? For example: 8.14.1 - don't just write v8

11.3.1

### Bug summary

The DataList property does not take user permissions into account. When a user can (for example) only view and publish a node, a datalist can still be edited by clicking on the label of the property.

I am unsure if this is relevant to any other Contentment editor type.

### Steps to reproduce

- Create a ContentType that has a Contentment DataList property (with List editor: Item Picker and enable Multiple selection, the datasource does not matter)
- Create a page of the ContentType
- Create a UserGroup that can only view and publish the just created page (for example via the granular permissions)
- Create a User that has this UserGroup assigned
- Now login as this User and access the page
- The Datalist property should be grayed-out, but when I click on the label the Overlay still opens and you can add an item
- Since the User has publish permissions it can publish this change, while it shouldn't have access to edit the any of the properties

### Expected result / actual result

Expected: The user cannot edit the property
Actual: The user can edit the property through clicking on the label of the property

### Do you have Umbraco ModelsBuilder enabled?

- [X] Yes, it is enabled.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by leekelleher** [comment] 2023-05-12 11:54
Thanks for raising this @jerpenol. I've never looked into user permissions for property-editors, I thought that was something handled by Umbraco at content-type level.

I'd appreciate any advice (from anyone reading this) on how to go about achieving this.

**Comment by leekelleher** [comment] 2023-08-24 11:23
Hi @jerpenol, I'm finally getting around to looking into this. I have a question about...

> Create a UserGroup that can only view and publish the just created page (for example via the granular permissions)

Would you be able to clarify which permissions need to be set for the restricted user group?

![Screenshot 2023-08-24 122025](https://github.com/leekelleher/umbraco-contentment/assets/209066/06c15c92-af68-40a8-b280-15177b82e312)

I'm assuming **Browse Node** and **Publish**? But when I try these, the user (in that user group) can still edit the page's properties. So I'm unsure how this should be configured. 😕

**Comment by jerpenol** [comment] 2023-08-24 11:57
@leekelleher That's weird, on my end I created a new UserGroup with the exact same permissions and when I log in with that user I cannot actually adjust the properties, the fields are not disabled, but I cannot adjust text in a textstring for example.

**Comment by leekelleher** [comment] 2023-09-05 16:09
I've tried this again, even on different Umbraco versions (8, 10, and 12), and I still can't get it to work (even with Umbraco's built-in property-editors).  I'm completely unsure how the user-group's permissions are meant to be configured in order to lock down properties (e.g. read-only) on a node.

---

I'm tempted to close this off as a `cant-fix` - as I'm stumped on how I could resolve it.

**Comment by leekelleher** [comment] 2023-09-05 16:12
Closing off this issue, as I am unable to reproduce the underlying test scenario - and can not offer any workaround or resolution.

If someone knows how to resolve this, please do feel free to submit a pull request. 🙏

**Closed by leekelleher** 2023-09-05 16:12 UTC
Labels: bug-report, help wanted, cant-fix
